### PR TITLE
fixed minimal problems

### PR DESCRIPTION
**Pull request by rodrigopmatias**
Problem fixed:

image

### CODE REVIEW

**Comment by brumm** [comment]
Hey! Thank you so much for contributing!

I have no idea why I never got a notification about your PR, but I'll take a look soon. Thanks again!

**Comment by brumm** [comment]
Nice, this seems to fix the overlapping issue. Good work!
Could you explain why you tweaked the repository url?

**Comment by rodrigopmatias** [comment]
Sorry for the delay in answering your question.

The repository address was not compliant with **npm** and with **apm**, this can be caught in the link that appears in the configuration of the plugin inside the **atom**, but it still points to the correct repository.

**Comment by brumm** [comment]
Thanks a lot!

**Pull request merged**
